server:
  port: 8085
spring:
  application:
    name: seckill-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Admin123!
    url: jdbc:mysql://localhost:3306/seckill
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
rocketmq:
  name-server: 192.168.88.131:9876
mybatis:
  mapper-locations: classpath:mapper/*.xml
  #configuration:
  #  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 日志打印输出
